"""RAUM27 mathematical core: rational-space geometry and fractal attractors.

This package implements the parts of the RAUM27 notes that are ordinary,
checkable mathematics (a multiplicative group of positive rationals, a
3-adic/9-adic scale hierarchy, cube symmetry, iterated function systems,
and a rational Taylor approximation of sine).

It deliberately does NOT implement the predictive or metaphysical claims
found in the source notes (forecasting random draws, "resonance",
"consciousness", or any claim of physical signal transfer). Those claims
are either unfalsifiable or contradict basic probability theory, and are
out of scope for a benchmarkable codebase.
"""

from raum27.rational_space import involution, is_fixed_point
from raum27.scale_hierarchy import area_scale, digital_root, linear_scale, volume_scale
from raum27.cube_symmetry import (
    axis_cross_product,
    corner_directions,
    coupling_constant,
    cube_center,
    cube_volume,
    face_diagonal_midpoint,
    face_diagonal_squared,
    face_directions,
    pyramid_apex_to_corner_squared,
    pyramid_base_half_diagonal_squared,
    pyramid_height,
    pyramid_volume,
    space_diagonal_midpoint,
    space_diagonal_squared,
    space_diagonals,
    vector_equilibrium,
)
from raum27.ifs_attractor import AffineMap, IFS
from raum27.taylor import sin_taylor
from raum27.lotto_benchmark import (
    FingerprintKNNPredictor,
    RandomPredictor,
    backtest,
    expected_any_repeat_years,
    expected_matches,
    expected_specific_state_recurrence_years,
    match_probability,
    n_draw_states,
    permutation_test,
)
from raum27.autocorrelation_control import (
    PersistencePredictor,
    permutation_test_continuous,
    simulate_ar1,
)
from raum27.q144 import (
    NUM_STATES,
    State,
    all_states,
    operator_period,
    orbit,
    phi,
)
from raum27.clockfree_scheduler import (
    Process,
    Schedule,
    ScheduleResult,
    schedule_round_robin,
    schedule_run_to_completion,
)
from raum27.rubik_state import (
    axis_is_solved,
    axis_pairs,
    face_is_uniform,
    is_solved,
)
from raum27.phase_sync import (
    beat_period,
    is_synchronized,
    phase_angle,
    phase_difference,
)
from raum27.phasor_resonanzfilter import (
    correlation as phasor_correlation,
    energy as phasor_energy,
    fires as phasor_fires,
    matched_detector as phasor_matched_detector,
    state_at as phasor_state_at,
)
from raum27.rotationsebenen import (
    elementary_rotation,
    rotation_plane_count,
    rotation_planes,
)
from raum27.modulketten_zuverlaessigkeit import (
    chain_success_probability,
    simulate_greedy_chain,
)
from raum27.octahedron import (
    vertices as octahedron_vertices,
    faces as octahedron_faces,
    edges as octahedron_edges,
    euler_characteristic as octahedron_euler_characteristic,
    dual_cube_corners as octahedron_dual_cube_corners,
)
from raum27.cube_projection import (
    incidence_matrix as cube_incidence_matrix,
    m_6to8,
    m_8to6,
    composed_kernel as cube_projection_kernel,
    apply as apply_matrix,
    apply_driven as apply_driven_matrix,
)
from raum27.hyperoperationen import (
    addition as hyperop_addition,
    multiplication_as_repeated_addition as hyperop_multiplication,
    power_as_repeated_multiplication as hyperop_power,
    tetration_as_repeated_power as hyperop_tetration,
)
from raum27.kubus_6_8_gleichgewicht import (
    exploding_exponent_mismatch as kubus68_exploding_exponent_mismatch,
    find_equilibrium as kubus68_find_equilibrium,
    is_strictly_increasing_on_sample as kubus68_is_strictly_increasing_on_sample,
)
from raum27.kern_modul_v1 import (
    all_corners as kmv1_all_corners,
    complement_contribution as kmv1_complement_contribution,
    face_contribution as kmv1_face_contribution,
    face_diagonal as kmv1_face_diagonal,
    flip_x as kmv1_flip_x,
    flip_y as kmv1_flip_y,
    flip_z as kmv1_flip_z,
    octant_solid_angle as kmv1_octant_solid_angle,
    parity as kmv1_parity,
    reachable as kmv1_reachable,
    redundancy_holds as kmv1_redundancy_holds,
    space_diagonal as kmv1_space_diagonal,
    tdoa_position as kmv1_tdoa_position,
)
from raum27.basisoperationen import hole_wert as basisoperationen_hole_wert
from raum27.kern_modul_v2 import (
    averaged_reading as kmv2_averaged_reading,
    bisect_rays as kmv2_bisect_rays,
    false_positive_counts as kmv2_false_positive_counts,
    find_period as kmv2_find_period,
    initial_rays as kmv2_initial_rays,
    is_evenly_spaced as kmv2_is_evenly_spaced,
    reconstruct_corners as kmv2_reconstruct_corners,
    reconstruct_face_directions as kmv2_reconstruct_face_directions,
    redundancy_corrected_reading as kmv2_redundancy_corrected_reading,
    redundancy_deviation as kmv2_redundancy_deviation,
    redundancy_state as kmv2_redundancy_state,
    rotate_about_x as kmv2_rotate_about_x,
    rotate_about_y as kmv2_rotate_about_y,
    tdoa_position as kmv2_tdoa_position,
    velocity_from_wavelength_and_frequency as kmv2_velocity_from_wavelength_and_frequency,
    wavelength_from_velocity_and_frequency as kmv2_wavelength_from_velocity_and_frequency,
)

__all__ = [
    "involution",
    "is_fixed_point",
    "linear_scale",
    "area_scale",
    "volume_scale",
    "digital_root",
    "face_directions",
    "corner_directions",
    "vector_equilibrium",
    "coupling_constant",
    "axis_cross_product",
    "cube_center",
    "face_diagonal_midpoint",
    "face_diagonal_squared",
    "space_diagonal_midpoint",
    "space_diagonal_squared",
    "space_diagonals",
    "cube_volume",
    "pyramid_apex_to_corner_squared",
    "pyramid_base_half_diagonal_squared",
    "pyramid_height",
    "pyramid_volume",
    "AffineMap",
    "IFS",
    "sin_taylor",
    "FingerprintKNNPredictor",
    "RandomPredictor",
    "backtest",
    "expected_any_repeat_years",
    "expected_matches",
    "expected_specific_state_recurrence_years",
    "match_probability",
    "n_draw_states",
    "permutation_test",
    "PersistencePredictor",
    "permutation_test_continuous",
    "simulate_ar1",
    "NUM_STATES",
    "State",
    "all_states",
    "operator_period",
    "orbit",
    "phi",
    "Process",
    "Schedule",
    "ScheduleResult",
    "schedule_round_robin",
    "schedule_run_to_completion",
    "axis_is_solved",
    "axis_pairs",
    "face_is_uniform",
    "is_solved",
    "beat_period",
    "is_synchronized",
    "phase_angle",
    "phase_difference",
    "phasor_correlation",
    "phasor_energy",
    "phasor_fires",
    "phasor_matched_detector",
    "phasor_state_at",
    "elementary_rotation",
    "rotation_plane_count",
    "rotation_planes",
    "chain_success_probability",
    "simulate_greedy_chain",
    "octahedron_vertices",
    "octahedron_faces",
    "octahedron_edges",
    "octahedron_euler_characteristic",
    "octahedron_dual_cube_corners",
    "cube_incidence_matrix",
    "m_6to8",
    "m_8to6",
    "cube_projection_kernel",
    "apply_matrix",
    "apply_driven_matrix",
    "kmv1_all_corners",
    "kmv1_complement_contribution",
    "kmv1_face_contribution",
    "kmv1_face_diagonal",
    "kmv1_flip_x",
    "kmv1_flip_y",
    "kmv1_flip_z",
    "kmv1_octant_solid_angle",
    "kmv1_parity",
    "kmv1_reachable",
    "kmv1_redundancy_holds",
    "kmv1_space_diagonal",
    "kmv1_tdoa_position",
    "kmv2_averaged_reading",
    "kmv2_bisect_rays",
    "kmv2_false_positive_counts",
    "kmv2_find_period",
    "kmv2_initial_rays",
    "kmv2_is_evenly_spaced",
    "kmv2_reconstruct_corners",
    "kmv2_reconstruct_face_directions",
    "kmv2_redundancy_corrected_reading",
    "kmv2_redundancy_deviation",
    "kmv2_redundancy_state",
    "kmv2_rotate_about_x",
    "kmv2_rotate_about_y",
    "kmv2_tdoa_position",
    "kmv2_velocity_from_wavelength_and_frequency",
    "kmv2_wavelength_from_velocity_and_frequency",
    "basisoperationen_hole_wert",
    "hyperop_addition",
    "hyperop_multiplication",
    "hyperop_power",
    "hyperop_tetration",
    "kubus68_exploding_exponent_mismatch",
    "kubus68_find_equilibrium",
    "kubus68_is_strictly_increasing_on_sample",
]
